name: Workflow Essentials
run-name: ${{ github.actor }} is testing essential workflow items
on: push
jobs:
  upload-artifact:
    name: Upload artifact
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
  download-artifact:
    name: Download Artifact
    runs-on: ubuntu-latest
    needs: upload-artifact
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file
      - shell: bash
        run: |
          ls -R
          cat output.log
